# Generated by Django 6.0.3 on 2026-03-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userprofile_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('color', models.CharField(default='#94a3b8', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manual_badges',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='polls.badge'),
        ),
    ]
